name: MSBuild

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure Tests
      run: cmake -S test -B test/build

    - name: Build Tests
      run: cmake --build test/build --config Debug

    - name: Run Tests
      run: ctest --test-dir test/build -C Debug --output-on-failure

  build:
    needs: test
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release, ReleaseAVX2, ReleaseFreetype, ReleaseFreetypeAVX2]
        platform: [x64]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore Spxarky.sln

    - name: Build
      run: msbuild Spxarky.sln /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.configuration }}
    
    - uses: actions/upload-artifact@v4
      with:
        name: Spxarky${{ matrix.platform }}${{ matrix.configuration }}
        path: output/${{ matrix.platform }}/${{ matrix.configuration }}/*.dll
    
    - uses: actions/upload-artifact@v4
      with:
        name: Spxarky${{ matrix.platform }}${{ matrix.configuration }}PDB
        path: output/${{ matrix.platform }}/${{ matrix.configuration }}/*.pdb