#pragma once
#include "CBasePlayer.h"
#include "CMultiPlayerAnimState.h"

#define PLAYER_ORIGIN_COMPRESSION 0.125f

MAKE_SIGNATURE(CTFPlayer_IsPlayerOnSteamFriendsList, XS("client.dll"), XS("40 57 48 81 EC ? ? ? ? 48 8B FA E8"), 0x0);
MAKE_SIGNATURE(TeamFortress_CalculateMaxSpeed, XS("client.dll"), XS("40 53 41 56 41 57 48 81 EC ? ? ? ? 48 83 3D"), 0x0);
MAKE_SIGNATURE(CTFPlayer_GetMaxAmmo, XS("client.dll"), XS("48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC ? 48 63 FA 48 8B F1"), 0x0);
MAKE_SIGNATURE(CTFPlayer_UpdateClientSideAnimation, XS("client.dll"), XS("48 89 5C 24 ? 57 48 83 EC ? 48 8B D9 E8 ? ? ? ? 48 8B F8 48 85 C0 74 ? 48 8B 00 48 8B CF FF 90 ? ? ? ? 84 C0 75 ? 33 FF 48 3B DF"), 0x0);
MAKE_SIGNATURE(CTFPlayer_GetEffectiveInvisibilityLevel, XS("client.dll"), XS("40 57 48 83 EC ? 0F 29 7C 24"), 0x0);
MAKE_SIGNATURE(CTFPlayer_UpdateWearables, XS("client.dll"), XS("40 53 48 83 EC ? 48 8B D9 E8 ? ? ? ? 48 8B 03 48 8B CB FF 90 ? ? ? ? 4C 8D 0D ? ? ? ? C7 44 24 ? ? ? ? ? 48 8B C8 4C 8D 05 ? ? ? ? 33 D2 E8 ? ? ? ? 48 85 C0"), 0x0);

class CTFPlayer : public CBasePlayer
{
public:
	NETVAR(m_bSaveMeParity, bool, XS("CTFPlayer"), XS("m_bSaveMeParity"));
	NETVAR(m_bIsMiniBoss, bool, XS("CTFPlayer"), XS("m_bIsMiniBoss"));
	NETVAR(m_bIsABot, bool, XS("CTFPlayer"), XS("m_bIsABot"));
	NETVAR(m_nBotSkill, int, XS("CTFPlayer"), XS("m_nBotSkill"));
	NETVAR(m_nWaterLevel, byte, XS("CTFPlayer"), XS("m_nWaterLevel"));
	NETVAR(m_hRagdoll, EHANDLE, XS("CTFPlayer"), XS("m_hRagdoll"));
	NETVAR(m_PlayerClass, void*, XS("CTFPlayer"), XS("m_PlayerClass"));
	NETVAR(m_iClass, int, XS("CTFPlayer"), XS("m_iClass"));
	NETVAR(m_iszClassIcon, const char*, XS("CTFPlayer"), XS("m_iszClassIcon"));
	NETVAR(m_iszCustomModel, const char*, XS("CTFPlayer"), XS("m_iszCustomModel"));
	NETVAR(m_vecCustomModelOffset, Vec3, XS("CTFPlayer"), XS("m_vecCustomModelOffset"));
	NETVAR(m_angCustomModelRotation, Vec3, XS("CTFPlayer"), XS("m_angCustomModelRotation"));
	NETVAR(m_bCustomModelRotates, bool, XS("CTFPlayer"), XS("m_bCustomModelRotates"));
	NETVAR(m_bCustomModelRotationSet, bool, XS("CTFPlayer"), XS("m_bCustomModelRotationSet"));
	NETVAR(m_bCustomModelVisibleToSelf, bool, XS("CTFPlayer"), XS("m_bCustomModelVisibleToSelf"));
	NETVAR(m_bUseClassAnimations, bool, XS("CTFPlayer"), XS("m_bUseClassAnimations"));
	NETVAR(m_iClassModelParity, int, XS("CTFPlayer"), XS("m_iClassModelParity"));
	NETVAR_EMBED(m_Shared, void*, XS("CTFPlayer"), XS("m_Shared"));
	NETVAR(m_nPlayerCond, int, XS("CTFPlayer"), XS("m_nPlayerCond"));
	NETVAR(m_bJumping, bool, XS("CTFPlayer"), XS("m_bJumping"));
	NETVAR(m_nNumHealers, int, XS("CTFPlayer"), XS("m_nNumHealers"));
	NETVAR(m_iCritMult, int, XS("CTFPlayer"), XS("m_iCritMult"));
	NETVAR(m_iAirDash, int, XS("CTFPlayer"), XS("m_iAirDash"));
	NETVAR(m_nAirDucked, int, XS("CTFPlayer"), XS("m_nAirDucked"));
	NETVAR(m_flDuckTimer, float, XS("CTFPlayer"), XS("m_flDuckTimer"));
	NETVAR(m_nPlayerState, int, XS("CTFPlayer"), XS("m_nPlayerState"));
	NETVAR(m_iDesiredPlayerClass, int, XS("CTFPlayer"), XS("m_iDesiredPlayerClass"));
	NETVAR(m_flMovementStunTime, float, XS("CTFPlayer"), XS("m_flMovementStunTime"));
	NETVAR(m_iMovementStunAmount, int, XS("CTFPlayer"), XS("m_iMovementStunAmount"));
	NETVAR(m_iMovementStunParity, int, XS("CTFPlayer"), XS("m_iMovementStunParity"));
	NETVAR(m_hStunner, EHANDLE, XS("CTFPlayer"), XS("m_hStunner"));
	NETVAR(m_iStunFlags, int, XS("CTFPlayer"), XS("m_iStunFlags"));
	NETVAR(m_nArenaNumChanges, int, XS("CTFPlayer"), XS("m_nArenaNumChanges"));
	NETVAR(m_bArenaFirstBloodBoost, bool, XS("CTFPlayer"), XS("m_bArenaFirstBloodBoost"));
	NETVAR(m_iWeaponKnockbackID, int, XS("CTFPlayer"), XS("m_iWeaponKnockbackID"));
	NETVAR(m_bLoadoutUnavailable, bool, XS("CTFPlayer"), XS("m_bLoadoutUnavailable"));
	NETVAR(m_iItemFindBonus, int, XS("CTFPlayer"), XS("m_iItemFindBonus"));
	NETVAR(m_bShieldEquipped, bool, XS("CTFPlayer"), XS("m_bShieldEquipped"));
	NETVAR(m_bParachuteEquipped, bool, XS("CTFPlayer"), XS("m_bParachuteEquipped"));
	NETVAR(m_iNextMeleeCrit, int, XS("CTFPlayer"), XS("m_iNextMeleeCrit"));
	NETVAR(m_iDecapitations, int, XS("CTFPlayer"), XS("m_iDecapitations"));
	NETVAR(m_iRevengeCrits, int, XS("CTFPlayer"), XS("m_iRevengeCrits"));
	NETVAR(m_iDisguiseBody, int, XS("CTFPlayer"), XS("m_iDisguiseBody"));
	NETVAR(m_hCarriedObject, EHANDLE, XS("CTFPlayer"), XS("m_hCarriedObject"));
	NETVAR(m_bCarryingObject, bool, XS("CTFPlayer"), XS("m_bCarryingObject"));
	NETVAR(m_flNextNoiseMakerTime, float, XS("CTFPlayer"), XS("m_flNextNoiseMakerTime"));
	NETVAR(m_iSpawnRoomTouchCount, int, XS("CTFPlayer"), XS("m_iSpawnRoomTouchCount"));
	NETVAR(m_iKillCountSinceLastDeploy, int, XS("CTFPlayer"), XS("m_iKillCountSinceLastDeploy"));
	NETVAR(m_flFirstPrimaryAttack, float, XS("CTFPlayer"), XS("m_flFirstPrimaryAttack"));
	NETVAR(m_flEnergyDrinkMeter, float, XS("CTFPlayer"), XS("m_flEnergyDrinkMeter"));
	NETVAR(m_flHypeMeter, float, XS("CTFPlayer"), XS("m_flHypeMeter"));
	NETVAR(m_flChargeMeter, float, XS("CTFPlayer"), XS("m_flChargeMeter"));
	NETVAR(m_flInvisChangeCompleteTime, float, XS("CTFPlayer"), XS("m_flInvisChangeCompleteTime"));
	NETVAR(m_nDisguiseTeam, int, XS("CTFPlayer"), XS("m_nDisguiseTeam"));
	NETVAR(m_nDisguiseClass, int, XS("CTFPlayer"), XS("m_nDisguiseClass"));
	NETVAR(m_nDisguiseSkinOverride, int, XS("CTFPlayer"), XS("m_nDisguiseSkinOverride"));
	NETVAR(m_nMaskClass, int, XS("CTFPlayer"), XS("m_nMaskClass"));
	NETVAR(m_iDisguiseTargetIndex, int, XS("CTFPlayer"), XS("m_iDisguiseTargetIndex"));
	NETVAR(m_iDisguiseHealth, int, XS("CTFPlayer"), XS("m_iDisguiseHealth"));
	NETVAR(m_bFeignDeathReady, bool, XS("CTFPlayer"), XS("m_bFeignDeathReady"));
	NETVAR(m_hDisguiseWeapon, EHANDLE, XS("CTFPlayer"), XS("m_hDisguiseWeapon"));
	NETVAR(m_nTeamTeleporterUsed, int, XS("CTFPlayer"), XS("m_nTeamTeleporterUsed"));
	NETVAR(m_flCloakMeter, float, XS("CTFPlayer"), XS("m_flCloakMeter"));
	NETVAR(m_flSpyTranqBuffDuration, float, XS("CTFPlayer"), XS("m_flSpyTranqBuffDuration"));
	NETVAR(m_nDesiredDisguiseTeam, int, XS("CTFPlayer"), XS("m_nDesiredDisguiseTeam"));
	NETVAR(m_nDesiredDisguiseClass, int, XS("CTFPlayer"), XS("m_nDesiredDisguiseClass"));
	NETVAR(m_flStealthNoAttackExpire, float, XS("CTFPlayer"), XS("m_flStealthNoAttackExpire"));
	NETVAR(m_flStealthNextChangeTime, float, XS("CTFPlayer"), XS("m_flStealthNextChangeTime"));
	NETVAR(m_bLastDisguisedAsOwnTeam, bool, XS("CTFPlayer"), XS("m_bLastDisguisedAsOwnTeam"));
	NETVAR(m_flRageMeter, float, XS("CTFPlayer"), XS("m_flRageMeter"));
	NETVAR(m_bRageDraining, bool, XS("CTFPlayer"), XS("m_bRageDraining"));
	NETVAR(m_flNextRageEarnTime, float, XS("CTFPlayer"), XS("m_flNextRageEarnTime"));
	NETVAR(m_bInUpgradeZone, bool, XS("CTFPlayer"), XS("m_bInUpgradeZone"));
	NETVAR(m_flItemChargeMeter, void*, XS("CTFPlayer"), XS("m_flItemChargeMeter"));
	NETVAR(m_bPlayerDominated, void*, XS("CTFPlayer"), XS("m_bPlayerDominated"));
	NETVAR(m_bPlayerDominatingMe, void*, XS("CTFPlayer"), XS("m_bPlayerDominatingMe"));
	NETVAR(m_ScoreData, void*, XS("CTFPlayer"), XS("m_ScoreData"));
	NETVAR(m_iCaptures, int, XS("CTFPlayer"), XS("m_iCaptures"));
	NETVAR(m_iDefenses, int, XS("CTFPlayer"), XS("m_iDefenses"));
	NETVAR(m_iKills, int, XS("CTFPlayer"), XS("m_iKills"));
	NETVAR(m_iDeaths, int, XS("CTFPlayer"), XS("m_iDeaths"));
	NETVAR(m_iSuicides, int, XS("CTFPlayer"), XS("m_iSuicides"));
	NETVAR(m_iDominations, int, XS("CTFPlayer"), XS("m_iDominations"));
	NETVAR(m_iRevenge, int, XS("CTFPlayer"), XS("m_iRevenge"));
	NETVAR(m_iBuildingsBuilt, int, XS("CTFPlayer"), XS("m_iBuildingsBuilt"));
	NETVAR(m_iBuildingsDestroyed, int, XS("CTFPlayer"), XS("m_iBuildingsDestroyed"));
	NETVAR(m_iHeadshots, int, XS("CTFPlayer"), XS("m_iHeadshots"));
	NETVAR(m_iBackstabs, int, XS("CTFPlayer"), XS("m_iBackstabs"));
	NETVAR(m_iHealPoints, int, XS("CTFPlayer"), XS("m_iHealPoints"));
	NETVAR(m_iInvulns, int, XS("CTFPlayer"), XS("m_iInvulns"));
	NETVAR(m_iTeleports, int, XS("CTFPlayer"), XS("m_iTeleports"));
	NETVAR(m_iResupplyPoints, int, XS("CTFPlayer"), XS("m_iResupplyPoints"));
	NETVAR(m_iKillAssists, int, XS("CTFPlayer"), XS("m_iKillAssists"));
	NETVAR(m_iPoints, int, XS("CTFPlayer"), XS("m_iPoints"));
	NETVAR(m_iBonusPoints, int, XS("CTFPlayer"), XS("m_iBonusPoints"));
	NETVAR(m_iDamageDone, int, XS("CTFPlayer"), XS("m_iDamageDone"));
	NETVAR(m_iCrits, int, XS("CTFPlayer"), XS("m_iCrits"));
	NETVAR(m_RoundScoreData, void*, XS("CTFPlayer"), XS("m_RoundScoreData"));
	NETVAR(m_ConditionList, void*, XS("CTFPlayer"), XS("m_ConditionList"));
	NETVAR(_condition_bits, int, XS("CTFPlayer"), XS("_condition_bits"));
	NETVAR(m_iTauntIndex, int, XS("CTFPlayer"), XS("m_iTauntIndex"));
	NETVAR(m_iTauntConcept, int, XS("CTFPlayer"), XS("m_iTauntConcept"));
	NETVAR(m_nPlayerCondEx, int, XS("CTFPlayer"), XS("m_nPlayerCondEx"));
	NETVAR(m_iStunIndex, int, XS("CTFPlayer"), XS("m_iStunIndex"));
	NETVAR(m_nHalloweenBombHeadStage, int, XS("CTFPlayer"), XS("m_nHalloweenBombHeadStage"));
	NETVAR(m_nPlayerCondEx2, int, XS("CTFPlayer"), XS("m_nPlayerCondEx2"));
	NETVAR(m_nPlayerCondEx3, int, XS("CTFPlayer"), XS("m_nPlayerCondEx3"));
	NETVAR(m_nStreaks, void*, XS("CTFPlayer"), XS("m_nStreaks"));
	NETVAR(m_unTauntSourceItemID_Low, int, XS("CTFPlayer"), XS("m_unTauntSourceItemID_Low"));
	NETVAR(m_unTauntSourceItemID_High, int, XS("CTFPlayer"), XS("m_unTauntSourceItemID_High"));
	NETVAR(m_flRuneCharge, float, XS("CTFPlayer"), XS("m_flRuneCharge"));
	NETVAR(m_bHasPasstimeBall, bool, XS("CTFPlayer"), XS("m_bHasPasstimeBall"));
	NETVAR(m_bIsTargetedForPasstimePass, bool, XS("CTFPlayer"), XS("m_bIsTargetedForPasstimePass"));
	NETVAR(m_hPasstimePassTarget, EHANDLE, XS("CTFPlayer"), XS("m_hPasstimePassTarget"));
	NETVAR(m_askForBallTime, float, XS("CTFPlayer"), XS("m_askForBallTime"));
	NETVAR(m_bKingRuneBuffActive, bool, XS("CTFPlayer"), XS("m_bKingRuneBuffActive"));
	NETVAR(m_nPlayerCondEx4, int, XS("CTFPlayer"), XS("m_nPlayerCondEx4"));
	NETVAR(m_flHolsterAnimTime, float, XS("CTFPlayer"), XS("m_flHolsterAnimTime"));
	NETVAR(m_hSwitchTo, EHANDLE, XS("CTFPlayer"), XS("m_hSwitchTo"));
	NETVAR(m_hItem, EHANDLE, XS("CTFPlayer"), XS("m_hItem"));
	NETVAR(m_bIsCoaching, bool, XS("CTFPlayer"), XS("m_bIsCoaching"));
	NETVAR(m_hCoach, EHANDLE, XS("CTFPlayer"), XS("m_hCoach"));
	NETVAR(m_hStudent, EHANDLE, XS("CTFPlayer"), XS("m_hStudent"));
	NETVAR(m_nCurrency, int, XS("CTFPlayer"), XS("m_nCurrency"));
	NETVAR(m_nExperienceLevel, int, XS("CTFPlayer"), XS("m_nExperienceLevel"));
	NETVAR(m_nExperienceLevelProgress, int, XS("CTFPlayer"), XS("m_nExperienceLevelProgress"));
	NETVAR(m_bMatchSafeToLeave, bool, XS("CTFPlayer"), XS("m_bMatchSafeToLeave"));
	NETVAR(m_vecOrigin, Vec3, XS("CTFPlayer"), XS("m_vecOrigin"));
	NETVAR(m_angEyeAngles, Vec3, XS("CTFPlayer"), XS("m_angEyeAngles[0]"));
	NETVAR(m_angEyeAnglesX, float, XS("CTFPlayer"), XS("m_angEyeAngles[0]"));
	NETVAR(m_angEyeAnglesY, float, XS("CTFPlayer"), XS("m_angEyeAngles[1]"));
	NETVAR(m_bAllowMoveDuringTaunt, bool, XS("CTFPlayer"), XS("m_bAllowMoveDuringTaunt"));
	NETVAR(m_bIsReadyToHighFive, bool, XS("CTFPlayer"), XS("m_bIsReadyToHighFive"));
	NETVAR(m_hHighFivePartner, EHANDLE, XS("CTFPlayer"), XS("m_hHighFivePartner"));
	NETVAR(m_nForceTauntCam, int, XS("CTFPlayer"), XS("m_nForceTauntCam"));
	NETVAR(m_flTauntYaw, float, XS("CTFPlayer"), XS("m_flTauntYaw"));
	NETVAR(m_nActiveTauntSlot, int, XS("CTFPlayer"), XS("m_nActiveTauntSlot"));
	NETVAR(m_iTauntItemDefIndex, int, XS("CTFPlayer"), XS("m_iTauntItemDefIndex"));
	NETVAR(m_flCurrentTauntMoveSpeed, float, XS("CTFPlayer"), XS("m_flCurrentTauntMoveSpeed"));
	NETVAR(m_flVehicleReverseTime, float, XS("CTFPlayer"), XS("m_flVehicleReverseTime"));
	NETVAR(m_flMvMLastDamageTime, float, XS("CTFPlayer"), XS("m_flMvMLastDamageTime"));
	NETVAR(m_flLastDamageTime, float, XS("CTFPlayer"), XS("m_flLastDamageTime"));
	NETVAR(m_bInPowerPlay, bool, XS("CTFPlayer"), XS("m_bInPowerPlay"));
	NETVAR(m_iSpawnCounter, int, XS("CTFPlayer"), XS("m_iSpawnCounter"));
	NETVAR(m_bFlipViewModels, bool, XS("CTFPlayer"), XS("m_bFlipViewModels"));
	NETVAR(m_bArenaSpectator, bool, XS("CTFPlayer"), XS("m_bArenaSpectator"));
	NETVAR_EMBED(m_AttributeManager, void*, XS("CTFPlayer"), XS("m_AttributeManager"));
	NETVAR(m_hOuter, EHANDLE, XS("CTFPlayer"), XS("m_hOuter"));
	NETVAR(m_ProviderType, int, XS("CTFPlayer"), XS("m_ProviderType"));
	NETVAR(m_iReapplyProvisionParity, int, XS("CTFPlayer"), XS("m_iReapplyProvisionParity"));
	NETVAR(m_flHeadScale, float, XS("CTFPlayer"), XS("m_flHeadScale"));
	NETVAR(m_flTorsoScale, float, XS("CTFPlayer"), XS("m_flTorsoScale"));
	NETVAR(m_flHandScale, float, XS("CTFPlayer"), XS("m_flHandScale"));
	NETVAR(m_bUseBossHealthBar, bool, XS("CTFPlayer"), XS("m_bUseBossHealthBar"));
	NETVAR(m_bUsingVRHeadset, bool, XS("CTFPlayer"), XS("m_bUsingVRHeadset"));
	NETVAR(m_bForcedSkin, bool, XS("CTFPlayer"), XS("m_bForcedSkin"));
	NETVAR(m_nForcedSkin, int, XS("CTFPlayer"), XS("m_nForcedSkin"));
	NETVAR(m_bGlowEnabled, bool, XS("CTFPlayer"), XS("m_bGlowEnabled"));
	NETVAR(m_nActiveWpnClip, int, XS("CTFPlayer"), XS("m_nActiveWpnClip"));
	NETVAR(m_flKartNextAvailableBoost, float, XS("CTFPlayer"), XS("m_flKartNextAvailableBoost"));
	NETVAR(m_iKartHealth, int, XS("CTFPlayer"), XS("m_iKartHealth"));
	NETVAR(m_iKartState, int, XS("CTFPlayer"), XS("m_iKartState"));
	NETVAR(m_hGrapplingHookTarget, EHANDLE, XS("CTFPlayer"), XS("m_hGrapplingHookTarget"));
	NETVAR(m_hSecondaryLastWeapon, EHANDLE, XS("CTFPlayer"), XS("m_hSecondaryLastWeapon"));
	NETVAR(m_bUsingActionSlot, bool, XS("CTFPlayer"), XS("m_bUsingActionSlot"));
	NETVAR(m_flInspectTime, float, XS("CTFPlayer"), XS("m_flInspectTime"));
	NETVAR(m_flHelpmeButtonPressTime, float, XS("CTFPlayer"), XS("m_flHelpmeButtonPressTime"));
	NETVAR(m_iCampaignMedals, int, XS("CTFPlayer"), XS("m_iCampaignMedals"));
	NETVAR(m_iPlayerSkinOverride, int, XS("CTFPlayer"), XS("m_iPlayerSkinOverride"));
	NETVAR(m_bViewingCYOAPDA, bool, XS("CTFPlayer"), XS("m_bViewingCYOAPDA"));
	NETVAR(m_bRegenerating, bool, XS("CTFPlayer"), XS("m_bRegenerating"));
	NETVAR(m_hOffHandWeapon, EHANDLE, XS("CTFPlayer"), XS("m_hOffHandWeapon"));

	NETVAR_OFF(m_flInvisibility, float, XS("CTFPlayer"), XS("m_flInvisChangeCompleteTime"), -8);
	NETVAR_OFF(m_flPrevInvisibility, float, XS("CTFPlayer"), XS("m_flInvisChangeCompleteTime"), -4);
	NETVAR_OFF(m_flTankPressure, float, XS("CTFPlayer"), XS("m_Shared"), 636);
	NETVAR_OFF(m_PlayerAnimState, CTFPlayerAnimState*, XS("CTFPlayer"), XS("m_hItem"), -88);
	NETVAR_OFF(m_flPrevTauntYaw, float, XS("CTFPlayer"), XS("m_flTauntYaw"), 4);
	NETVAR_OFF(m_flLastMovementStunChange, float, XS("CTFPlayer"), XS("m_hItem"), -180);
	NETVAR_OFF(m_flStunLerpTarget, float, XS("CTFPlayer"), XS("m_hItem"), -184);
	NETVAR_OFF(m_bStunNeedsFadeOut, bool, XS("CTFPlayer"), XS("m_hItem"), -188);
	NETVAR_OFF(m_bTauntForceMoveForward, bool, XS("CTFPlayer"), XS("m_bAllowMoveDuringTaunt"), 1);
	NETVAR_OFF(m_flTauntForceMoveForwardSpeed, float, XS("CTFPlayer"), XS("m_bAllowMoveDuringTaunt"), 4);

	VIRTUAL(GetMaxHealth, int, 107, this);
	VIRTUAL(ThirdPersonSwitch, void, 256, this);

	SIGNATURE(IsPlayerOnSteamFriendsList, bool, CTFPlayer, this, this);
	SIGNATURE_ARGS(CalculateMaxSpeed, float, TeamFortress, (bool bIgnoreSpecialAbility = false), this, bIgnoreSpecialAbility);
	SIGNATURE_ARGS(GetMaxAmmo, int, CTFPlayer, (int iAmmoIndex, int iClassIndex = -1), this, iAmmoIndex, iClassIndex);
	SIGNATURE(UpdateClientSideAnimation, void, CTFPlayer, this);
	SIGNATURE(GetEffectiveInvisibilityLevel, float, CTFPlayer, this);
	SIGNATURE(UpdateWearables, void, CTFPlayer, this);

	Vec3 GetEyeAngles();
	Vec3 GetViewOffset(bool bScale = true); // use on nonlocal players
	bool InCond(ETFCond eCond);
	void AddCond(ETFCond eCond); // bits only
	void RemoveCond(ETFCond eCond); // bits only
	bool IsAGhost();
	bool IsTaunting();
	bool IsInvisible(float flValue = 1.f);
	bool IsInvulnerable();
	bool IsUbered();
	bool IsCritBoosted();
	bool IsMiniCritBoosted();
	bool IsMarked();
	bool CanAttack(bool bCloak = true, bool bLocal = true);
	float GetCritMult();
};

class CTFRagdoll : public CBaseFlex
{
public:
	NETVAR(m_hPlayer, EHANDLE, XS("CTFRagdoll"), XS("m_hPlayer"))
	NETVAR(m_vecRagdollOrigin, Vec3, XS("CTFRagdoll"), XS("m_vecRagdollOrigin"));
	NETVAR(m_iPlayerIndex, int, XS("CTFRagdoll"), XS("m_iPlayerIndex"));
	NETVAR(m_vecForce, Vec3, XS("CTFRagdoll"), XS("m_vecForce"));
	NETVAR(m_vecRagdollVelocity, Vec3, XS("CTFRagdoll"), XS("m_vecRagdollVelocity"));
	NETVAR(m_nForceBone, int, XS("CTFRagdoll"), XS("m_nForceBone"));
	NETVAR(m_bGib, bool, XS("CTFRagdoll"), XS("m_bGib"));
	NETVAR(m_bBurning, bool, XS("CTFRagdoll"), XS("m_bBurning"));
	NETVAR(m_bElectrocuted, bool, XS("CTFRagdoll"), XS("m_bElectrocuted"));
	NETVAR(m_bFeignDeath, bool, XS("CTFRagdoll"), XS("m_bFeignDeath"));
	NETVAR(m_bWasDisguised, bool, XS("CTFRagdoll"), XS("m_bWasDisguised"));
	NETVAR(m_bOnGround, bool, XS("CTFRagdoll"), XS("m_bOnGround"));
	NETVAR(m_bCloaked, bool, XS("CTFRagdoll"), XS("m_bCloaked"));
	NETVAR(m_bBecomeAsh, bool, XS("CTFRagdoll"), XS("m_bBecomeAsh"));
	NETVAR(m_iDamageCustom, int, XS("CTFRagdoll"), XS("m_iDamageCustom"));
	NETVAR(m_iTeam, int, XS("CTFRagdoll"), XS("m_iTeam"));
	NETVAR(m_iClass, int, XS("CTFRagdoll"), XS("m_iClass"));
	NETVAR(m_bGoldRagdoll, bool, XS("CTFRagdoll"), XS("m_bGoldRagdoll"));
	NETVAR(m_bIceRagdoll, bool, XS("CTFRagdoll"), XS("m_bIceRagdoll"));
	NETVAR(m_bCritOnHardHit, bool, XS("CTFRagdoll"), XS("m_bCritOnHardHit"));
	NETVAR(m_flHeadScale, float, XS("CTFRagdoll"), XS("m_flHeadScale"));
	NETVAR(m_flTorsoScale, float, XS("CTFRagdoll"), XS("m_flTorsoScale"));
	NETVAR(m_flHandScale, float, XS("CTFRagdoll"), XS("m_flHandScale"));

	NETVAR_OFF(m_bDissolving, bool, XS("CTFRagdoll"), XS("m_bFeignDeath"), -1);
};