#pragma once

// ---------------------------------------------------------------------------
// SecureString — runtime-encrypted sensitive string storage.
//
// Stores the content XOR'd with a 16-byte key generated by RAND_bytes() at
// Set() time.  The plaintext never lives in a heap buffer longer than the
// duration of a Get() call.  The internal key and data buffer are wiped with
// OPENSSL_cleanse() on destruction and reassignment.
//
// Thread safety: NOT thread-safe.  Each instance should be owned and accessed
// from a single thread, or callers must hold an external lock.
//
// Usage:
//   SecureString s;
//   s.Set("re_abc123...");      // encrypts in place; env var can be cleared
//   ...
//   {
//     std::string plain = s.Get();
//     use(plain);
//     OPENSSL_cleanse(plain.data(), plain.size()); // optional extra hygiene
//   }
// ---------------------------------------------------------------------------

#include <cstdint>
#include <cstring>
#include <string>
#include <string_view>
#include <vector>
#include <openssl/rand.h>
#include <openssl/crypto.h>

class SecureString
{
    uint8_t              m_xkey[16]{};
    std::vector<uint8_t> m_buf;

    void wipe() noexcept
    {
        OPENSSL_cleanse(m_xkey, sizeof(m_xkey));
        if (!m_buf.empty())
        {
            OPENSSL_cleanse(m_buf.data(), m_buf.size());
            m_buf.clear();
        }
    }

public:
    SecureString() = default;

    ~SecureString() { wipe(); }

    // Non-copyable — copying secrets is a bad pattern.
    SecureString(const SecureString&)            = delete;
    SecureString& operator=(const SecureString&) = delete;

    // Movable — transfers ownership and zeroes the source.
    SecureString(SecureString&& o) noexcept : m_buf(std::move(o.m_buf))
    {
        std::memcpy(m_xkey, o.m_xkey, sizeof(m_xkey));
        OPENSSL_cleanse(o.m_xkey, sizeof(o.m_xkey));
    }

    SecureString& operator=(SecureString&& o) noexcept
    {
        if (this != &o)
        {
            wipe();
            m_buf = std::move(o.m_buf);
            std::memcpy(m_xkey, o.m_xkey, sizeof(m_xkey));
            OPENSSL_cleanse(o.m_xkey, sizeof(o.m_xkey));
        }
        return *this;
    }

    bool   empty() const noexcept { return m_buf.empty(); }
    size_t size()  const noexcept { return m_buf.size(); }

    // Encrypt and store a new value, wiping the previous one.
    void Set(const char* s, size_t len)
    {
        wipe();
        if (!s || len == 0) return;
        RAND_bytes(m_xkey, sizeof(m_xkey));
        m_buf.resize(len);
        for (size_t i = 0; i < len; ++i)
            m_buf[i] = static_cast<uint8_t>(s[i]) ^ m_xkey[i % sizeof(m_xkey)];
    }

    void Set(const char* s)            { if (s) Set(s, std::strlen(s)); }
    void Set(const std::string& s)     { Set(s.data(), s.size()); }
    void Set(std::string_view s)       { Set(s.data(), s.size()); }

    // Decrypt and return the plaintext.  Use the result immediately.
    // In security-critical paths, call OPENSSL_cleanse(out.data(), out.size())
    // once finished to avoid leaving the secret on the heap.
    [[nodiscard]] std::string Get() const
    {
        std::string out(m_buf.size(), '\0');
        for (size_t i = 0; i < m_buf.size(); ++i)
            out[i] = static_cast<char>(m_buf[i] ^ m_xkey[i % sizeof(m_xkey)]);
        return out;
    }
};

// ---------------------------------------------------------------------------
// ClearEnv — zero an environment variable and remove it from the process
// environment so it cannot be read from /proc/self/environ after startup.
// ---------------------------------------------------------------------------
inline void ClearEnv(const char* name) noexcept
{
#ifdef _WIN32
    _putenv_s(name, "");
#else
    unsetenv(name);
#endif
}
